// Theme presets — mirrors renderers/themes.py but for PptxGenJS (inches, no EMU)
const THEMES = {
  tech_dark: {
    dark: true,
    bg:          '1E293B',
    bgDeep:      '0F172A',
    accent:      '0EA5E9',
    accent2:     '38BDF8',
    green:       '22C55E',
    indigo:      '6366F1',
    amber:       'F59E0B',
    red:         'EF4444',
    textPrimary: 'F1F5F9',
    textSecond:  '94A3B8',
    textMuted:   '64748B',
    cardBg:      '1E3A5F',
    cardBorder:  '334155',
    fontTitle:   'Microsoft YaHei UI',
    fontBody:    'Segoe UI',
    fontNum:     'Segoe UI',
  },
  corporate: {
    dark: false,
    bg:          'FFFFFF',
    bgDeep:      '1E3A5F',
    accent:      '1D4ED8',
    accent2:     '3B82F6',
    green:       '16A34A',
    indigo:      '4338CA',
    amber:       'D97706',
    red:         'DC2626',
    textPrimary: '0F172A',
    textSecond:  '334155',
    textMuted:   '64748B',
    cardBg:      'F8FAFC',
    cardBorder:  'CBD5E1',
    fontTitle:   'Microsoft YaHei UI',
    fontBody:    'Segoe UI',
    fontNum:     'Segoe UI',
  },
  warm: {
    dark: false,
    bg:          'FFFBF5',
    bgDeep:      '1C1408',
    accent:      'D97706',
    accent2:     'F59E0B',
    green:       '15803D',
    indigo:      '7C3AED',
    amber:       'B45309',
    red:         'DC2626',
    textPrimary: '1C1408',
    textSecond:  '78350F',
    textMuted:   '92400E',
    cardBg:      'FEF9EE',
    cardBorder:  'FDE68A',
    fontTitle:   'Microsoft YaHei UI',
    fontBody:    'Segoe UI',
    fontNum:     'Segoe UI',
  },
  purple: {
    dark: true,
    bg:          '1E1B4B',
    bgDeep:      '0F0A2E',
    accent:      '7C3AED',
    accent2:     'A78BFA',
    green:       '059669',
    indigo:      '4F46E5',
    amber:       'D97706',
    red:         'E11D48',
    textPrimary: 'EDE9FE',
    textSecond:  'C4B5FD',
    textMuted:   '7C3AED',
    cardBg:      '2D2A5E',
    cardBorder:  '3730A3',
    fontTitle:   'Microsoft YaHei UI',
    fontBody:    'Segoe UI',
    fontNum:     'Segoe UI',
  },
  forest: {
    dark: true,
    bg:          '052E16',
    bgDeep:      '022C22',
    accent:      '16A34A',
    accent2:     '22C55E',
    green:       '15803D',
    indigo:      '0D9488',
    amber:       'CA8A04',
    red:         'B91C1C',
    textPrimary: 'F0FDF4',
    textSecond:  'BBF7D0',
    textMuted:   '4ADE80',
    cardBg:      '0A4A22',
    cardBorder:  '14532D',
    fontTitle:   'Microsoft YaHei UI',
    fontBody:    'Segoe UI',
    fontNum:     'Segoe UI',
  },
  minimal: {
    dark: false,
    bg:          'FFFFFF',
    bgDeep:      '18181B',
    accent:      '18181B',
    accent2:     '3F3F46',
    green:       '16A34A',
    indigo:      '4338CA',
    amber:       'D97706',
    red:         'DC2626',
    textPrimary: '09090B',
    textSecond:  '52525B',
    textMuted:   'A1A1AA',
    cardBg:      'FAFAFA',
    cardBorder:  'E4E4E7',
    fontTitle:   'Calibri',
    fontBody:    'Calibri',
    fontNum:     'Calibri',
  },
  sunset: {
    dark: true,
    bg:          '1C0A00',
    bgDeep:      '0D0500',
    accent:      'EA580C',
    accent2:     'FB923C',
    green:       '65A30D',
    indigo:      'C026D3',
    amber:       'EAB308',
    red:         'E11D48',
    textPrimary: 'FFF7ED',
    textSecond:  'FED7AA',
    textMuted:   'C2410C',
    cardBg:      '2C1500',
    cardBorder:  '7C2D12',
    fontTitle:   'Microsoft YaHei UI',
    fontBody:    'Segoe UI',
    fontNum:     'Segoe UI',
  },
  ocean: {
    dark: true,
    bg:          '042F2E',
    bgDeep:      '021A19',
    accent:      '0D9488',
    accent2:     '2DD4BF',
    green:       '0EA5E9',
    indigo:      '0891B2',
    amber:       'CA8A04',
    red:         'B91C1C',
    textPrimary: 'F0FDFA',
    textSecond:  '99F6E4',
    textMuted:   '5EEAD4',
    cardBg:      '0A4744',
    cardBorder:  '134E4A',
    fontTitle:   'Microsoft YaHei UI',
    fontBody:    'Segoe UI',
    fontNum:     'Segoe UI',
  },
};

function getTheme(name) {
  return THEMES[name] || THEMES.tech_dark;
}

module.exports = { THEMES, getTheme };
